version: '2.4'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "2112:2112"
    mem_limit: 512m
    cpus: 1
    pids_limit: 256
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=leakless
      - POSTGRES_USER=leakless
      - POSTGRES_DB=leakless
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
